#!/usr/bin/env python3
"""
Generate themed publication pages from book/cv/publications.md

Usage:
    python scripts/generate_publications_md.py          # Generate files
    python scripts/generate_publications_md.py --check  # Check if files are up-to-date (for CI)
"""

import re
import sys
from pathlib import Path
from typing import Dict, List

# Category mapping based on keywords in titles/journals
HEALTHCARE_KEYWORDS = [
    'opioid', 'health', 'nurse', 'physician', 'pharmacist', 'hospital',
    'medicare', 'medicaid', 'medical', 'maternity', 'mental health',
    'substance', 'prescription', 'care', 'provider', 'clinical', 'pharmacy',
    'treatment', 'patient', 'doctor', 'nursing', 'practitioner'
]

INSTITUTIONAL_KEYWORDS = [
    'revolution', 'corruption', 'institutional', 'public choice',
    'political economy', 'regime', 'market legitimacy', 'library',
    'energy', 'shale', 'fracking', 'entrepreneurship', 'economic freedom',
    'startup', 'lumber', 'abortion', 'regulation', 'polyarchy', 'democracy',
    'governance', 'transparency', 'certificate-of-need', 'licensing'
]

EDUCATION_KEYWORDS = [
    'replicability', 'reproducibility', 'grading', 'teaching', 'education',
    'test scores', 'gender gap', 'university entrance', 'score', 'student',
    'learning', 'assessment', 'exam', 'classroom'
]

def classify_publication(text: str) -> str:
    """Classify a publication by examining its text"""
    text_lower = text.lower()

    # Count keyword matches
    healthcare_count = sum(1 for kw in HEALTHCARE_KEYWORDS if kw in text_lower)
    institutional_count = sum(1 for kw in INSTITUTIONAL_KEYWORDS if kw in text_lower)
    education_count = sum(1 for kw in EDUCATION_KEYWORDS if kw in text_lower)

    # Return category with most matches
    max_count = max(healthcare_count, institutional_count, education_count)

    if max_count == 0:
        return 'institutional'  # Default

    if healthcare_count == max_count:
        return 'healthcare'
    elif education_count == max_count:
        return 'education'
    else:
        return 'institutional'

def parse_publications(content: str) -> List[str]:
    """Extract numbered publications from markdown content"""
    # Find the publications list (starts after "# Publications")
    match = re.search(r'# Publications\n\n(.+)', content, re.DOTALL)
    if not match:
        return []

    pub_section = match.group(1)

    # Split by numbered items (1. 2. 3. etc)
    publications = re.split(r'\n\d+\.\s+', pub_section)
    # First item is empty, rest are publications
    return [pub.strip() for pub in publications[1:] if pub.strip()]

def categorize_publications(publications: List[str]) -> Dict[str, List[str]]:
    """Categorize publications into three themes"""
    categorized = {
        'healthcare': [],
        'institutional': [],
        'education': []
    }

    for pub in publications:
        category = classify_publication(pub)
        categorized[category].append(pub)

    return categorized

def generate_category_file(category: str, publications: List[str], output_path: Path):
    """Generate a themed publication markdown file"""

    titles = {
        'healthcare': 'Healthcare and Labor Economics',
        'institutional': 'Institutional Economics',
        'education': 'Education and Teaching Economics'
    }

    t = titles[category]
    # Frontmatter must be the first bytes in the file (no HTML comment above it), or MyST
    # will not parse YAML and will render "title: ..." as visible content.
    content = f"""---
title: {t}
---

<!-- Generated by scripts/generate_publications_md.py. Do not edit by hand. -->

"""

    for i, pub in enumerate(publications, 1):
        content += f"{i}. {pub}\n\n"

    output_path.write_text(content, encoding='utf-8')

def main():
    check_mode = '--check' in sys.argv

    # Paths
    base = Path(__file__).parent.parent
    source = base / 'book' / 'cv' / 'publications.md'
    output_dir = base / 'book' / 'cv'

    # Read source
    if not source.exists():
        print(f"Error: {source} not found")
        sys.exit(1)

    content = source.read_text(encoding='utf-8')

    # Parse and categorize
    publications = parse_publications(content)
    categorized = categorize_publications(publications)

    # Generate files
    files = {
        'healthcare': output_dir / 'publications-healthcare-labor-economics.md',
        'institutional': output_dir / 'publications-institutional-economics.md',
        'education': output_dir / 'publications-education-teaching-economics.md'
    }

    if check_mode:
        # Check if files are up-to-date
        all_match = True
        for category, filepath in files.items():
            if not filepath.exists():
                print(f"Error: {filepath} does not exist")
                all_match = False
                continue

            # Generate expected content
            import tempfile
            temp_path = Path(tempfile.mktemp())
            generate_category_file(category, categorized[category], temp_path)
            expected = temp_path.read_text(encoding='utf-8')
            actual = filepath.read_text(encoding='utf-8')
            temp_path.unlink()

            if expected != actual:
                print(f"Error: {filepath} is out of date")
                print("Run: python scripts/generate_publications_md.py")
                all_match = False

        if not all_match:
            sys.exit(1)
        else:
            print("All publication files are up-to-date")
    else:
        # Generate files
        for category, filepath in files.items():
            generate_category_file(category, categorized[category], filepath)
            print(f"Generated: {filepath}")

if __name__ == '__main__':
    main()
